name: Publishing Release
on:
  # release:
  #   # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#release
  #   types: [published]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_test_mac:
    name: Build and Test (macOS only)
    strategy:
      matrix:
        include:
          - os: macos-latest
            python: 3.6
            with_cc: OFF
            # - os: macos-latest
            #   python: 3.7
            #   with_cc: OFF
            # - os: macos-latest
            #   python: 3.8
            #   with_cc: OFF
            # - os: macos-latest
            #   python: 3.9
            #   with_cc: OFF
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Download Pre-Built LLVM 10.0.0
        run: |
          python misc/ci_download.py
          mkdir taichi-llvm
          cd taichi-llvm
          unzip ../taichi-llvm.zip
        env:
          CI_PLATFORM: ${{ matrix.os }}

      - name: Create Python Wheel
        run: |
          TAICHI_REPO_DIR=`pwd`
          export PATH=$TAICHI_REPO_DIR/taichi-llvm/bin/:$PATH
          export CXX=clang++
          # TODO: making changelog shouldn't depend on taichi.
          # We currently install taichi to make changelog when building the wheel.
          python -m pip install --user numpy pybind11 gitpython pytest
          python setup.py develop

      - name: Test
        run: |
          python examples/algorithm/laplace.py
          ti diagnose
          ti test -t2
          echo "${{ github.event.action }}"

          #    
          #- name: Archive Wheel Artifacts
          #  # https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts#uploading-build-and-test-artifacts
          #  uses: actions/upload-artifact@v2
          #  with:
          #    # While ${{ github.ref }} does provide the release tag, it is of
          #    # format `refs/tags/<tag_name>`, which isn't a valid file path.
          #    name: taichi-py${{ matrix.python }}-${{ matrix.os }}.whl
          #    path: dist/*.whl

      - name: Upload PyPI
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
          PYPI_PWD: "sjaaeriguhbnaeikd"
        run: |
          cd python
          python build.py upload

  build_and_test_windows:
    name: Build and Test (windows only)
    strategy:
      matrix:
        include:
          - os: windows-latest
            python: 3.6
            with_cc: OFF
            # - os: windows-latest
            #   python: 3.7
            #   with_cc: OFF
            # - os: windows-latest
            #   python: 3.8
            #   with_cc: OFF
            # - os: windows-latest
            #   python: 3.9
            #   with_cc: OFF
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install 7Zip PowerShell
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Python Wheel
        shell: powershell
        run: |
          cd C:\
          Remove-item alias:curl
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip -LO
          7z x taichi-llvm-10.0.0-msvc2019.zip -otaichi_llvm
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip -LO
          7z x clang-10.0.0-win.zip -otaichi_clang
          $env:PATH += ";C:\taichi_llvm\bin"
          $env:PATH += ";C:\taichi_clang\bin"
          clang --version
          cd D:\a\test_actions\test_actions
          python -m pip install --user numpy pybind11 gitpython pytest
          python setup.py develop
        env:
          CI_SETUP_CMAKE_ARGS: -G "Visual Studio 16 2019" -A x64 -DLLVM_DIR=C:\taichi_llvm\lib\cmake\llvm

      - name: Test
        shell: powershell
        run: |
          $env:PATH += ";C:\taichi_llvm\bin"
          $env:PATH += ";C:\taichi_clang\bin"
          python -c "import taichi"
          python examples/algorithm/laplace.py
          python bin/taichi diagnose
          python bin/taichi test
          echo "${{ github.event.action }}"

      - name: Upload PyPI
        shell: powershell
        env:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
          PYPI_PWD: "asdfasdjggaelkri"
        run: |
          cd python
          python build.py upload
