name: Test Schedule
on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "*/5 * * * *"

jobs:
  test_schedule:
    name: schedule test
    runs-on: windows-latest
    steps:
      - name: test
        shell: powershell
        env:
          PROD_PWD: "PROD"
          NIGHT_PWD: "NIGHTLY"
        run: |
          echo "${{ github.event.action }}"
          echo "Triggered every 5 minites!"
          if ([string]::IsNullOrEmpty("${{ github.event.action }}")) {$env:RELEASE = "$NIGHT_PWD"}
          if ([string]::IsNullOrEmpty("${{ github.event.action }}")) {echo "running nightly"}
          if ( -not [string]::IsNullOrEmpty("${{ github.event.action }}")) {$env:RELEASE = "$PROD_PWD"}
          if ( -not [string]::IsNullOrEmpty("${{ github.event.action }}")) {echo "running production"}
          echo "$env:RELEASE"

