name: Windows Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Install 7Zip PowerShell
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force -Verbose

      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: x64

      - name: Build
        shell: powershell
        run: |
          $env:TAICHI_REPO_DIR = "D:\a\test_actions\test_actions"
          Remove-item alias:curl
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/taichi-llvm-10.0.0-msvc2019.zip -LO
          7z x taichi-llvm-10.0.0-msvc2019.zip -otaichi_llvm
          curl --retry 10 --retry-delay 5 https://github.com/taichi-dev/taichi_assets/releases/download/llvm10/clang-10.0.0-win.zip -LO
          7z x clang-10.0.0-win.zip -otaichi_clang
          $env:PATH += ";C:\taichi_llvm\bin"
          $env:PATH += ";C:\taichi_clang\bin"
          $env:PYTHONPATH = "$env:TAICHI_REPO_DIR\python"
          $env:PATH += ";$env:TAICHI_REPO_DIR\bin"
          echo $env:TAICHI_REPO_DIR
          echo $env:PYTHONPATH
          echo $env:PATH
          clang --version
          cd D:\a\test_actions\test_actions
          python -m pip install numpy
          python -m pip install pybind11
          python misc/ci_setup.py ci
          mkdir build
          cd build
          cmake .. -G"Visual Studio 16 2019" -A x64 -DLLVM_DIR="C:\taichi_llvm\lib\cmake\llvm" 
          msbuild /p:Configuration=RelWithDebInfo /p:Platform=x64 /m taichi.sln
          cd ..
          python -c "import taichi"
          python examples/laplace.py
          python bin/taichi diagnose
          python bin/taichi test -Cvr2 -t2
